project:
  type: website

website:
  title: "R - Open Research Summer School"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - setup.qmd
      - the_big_picture.qmd
      - packages.qmd
      - load_data.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "Before the workshop"
        contents:
          - index.qmd
          - setup.qmd
      - section: "Getting Started"
        contents:
          - the_big_picture.qmd
          - exercise_overview.qmd
      - section: "Basics"
        contents:
        - section: "Basics"
          contents:
            - qmd/basics/basics.qmd
            - qmd/basics/basics_exercise.qmd
        - section: "Data structures"
          contents:
            - qmd/data_structures/data_structures.qmd
        - section: "rest"
          contents:
            - packages.qmd
            - load_data.qmd
      - section: "Data manipulation and transformation"
        contents:
          - subsetting.qmd
          - manipulation.qmd
      - section: "Advanced: Analysis and visualization"
        contents:
          - statistical_analyses.qmd
          - plotting.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto 

