project:
  type: website

website:
  title: "R - Open Research Summer School"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - setup.qmd
      - the_big_picture.qmd
      - packages.qmd
      - load_data.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "Before the workshop"
        contents:
          - index.qmd
          - setup.qmd
      - section: "Getting Started"
        contents:
          - section: "Workflow"
            contents:
              - qmd/workflow/workflow.qmd
              - qmd/workflow/workflow_exercise.qmd
          - section: "Overview"
            contents: 
              - the_big_picture.qmd
              - exercise_overview.qmd
      - section: "Basics"
        contents:
        - section: "Basics"
          contents:
            - qmd/basics/basics.qmd
            - qmd/basics/basics_exercise.qmd
        - section: "Data structures"
          contents:
            - qmd/data_structures/data_structures.qmd
            - qmd/data_structures/data_structures_exercise.qmd
        - section: "Packages"
          contents:
            - qmd/packages/packages.qmd
            - qmd/packages/packages_exercise.qmd
        - section: "Loading data"
          contents:
            - qmd/load_data/load_data.qmd
            - qmd/load_data/load_data_exercise.qmd

      - section: "Data manipulation and transformation"
        contents:
        - section: "Subsetting"
          contents:
            - qmd/subsetting/subsetting.qmd
            - qmd/subsetting/subsetting_exercise.qmd
        - section: "Merging"
          contents:
            - qmd/manipulation/manipulation.qmd
      - section: "Advanced: Analysis and visualization"
        contents:
          - qmd/statistical_analyses/statistical_analyses.qmd
          - qmd/plotting/plotting.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto 

