project:
  type: website

website:
  title: "R - Open Research Summer School"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index.qmd
        text: Getting Started
      - setup.qmd
      - the_big_picture.qmd
      - packages.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "Getting Started"
        contents:
          - setup.qmd
          - the_big_picture.qmd
          - packages.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto 

