project:
  type: website

website:
  title: "R - Open Research Summer School"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - setup.qmd
      - the_big_picture.qmd
      - packages.qmd
      - load_data.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Getting Started"
        contents:
          - setup.qmd
          - the_big_picture.qmd
      - section: "Basics"
        contents:
          - basics.qmd
          - data_types.qmd
          - data_structures.qmd
          - packages.qmd
          - load_data.qmd
      - section: "Data manipulation and transformation"
        contents:
          - subsetting.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto 

